const fs = require('fs');
const path = require('path');

// Configuration
const ROOT_DIR = './Figure';
const OUTPUT_FILE = './stimuli.js';
const VARIABLE_NAME = 'STIMULI_DATA';
const TOP_LEVEL = ['Face', 'Geometry', 'Natural_scene'];
const VALID_EXT = new Set(['.jpg', '.jpeg', '.png']);

function isValidFile(fileName) {
  const ext = path.extname(fileName).toLowerCase();
  if (!VALID_EXT.has(ext)) return false;
  if (fileName.startsWith('._')) return false;
  return true;
}

function walkCategory(catDir) {
  const files = [];
  const entries = fs.readdirSync(catDir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(catDir, entry.name);
    if (entry.isDirectory()) {
      files.push(...walkCategory(fullPath));
    } else if (entry.isFile() && isValidFile(entry.name)) {
      files.push(fullPath);
    }
  }
  return files;
}

try {
  const stimuli = [];

  for (const cat of TOP_LEVEL) {
    const catDir = path.join(ROOT_DIR, cat);
    console.log(`Scanning ${catDir}...`);
    const files = walkCategory(catDir);
    console.log(`  Found ${files.length} files in ${cat}.`);

    for (const filePath of files) {
      const relFromCat = path.relative(catDir, path.dirname(filePath));
      const relParts = relFromCat.split(path.sep).filter(Boolean);
      const setId = relParts.length ? relParts[0] : '__root';
      const webPath = `./${filePath.replace(/\\\\/g, '/').replace(/\\/g, '/')}`;

      stimuli.push({
        category: cat.toLowerCase(),
        set: setId,
        label: path.basename(filePath),
        src: webPath
      });
    }
  }

  const fileContent = `// Auto-generated by generate_stimuli.js\nwindow.${VARIABLE_NAME} = ${JSON.stringify(stimuli, null, 2)};`;
  fs.writeFileSync(OUTPUT_FILE, fileContent);
  console.log(`Successfully wrote ${stimuli.length} rows to ${OUTPUT_FILE}`);
  
} catch (err) {
  console.error('Error generating stimuli:', err);
}
